export const guildNames: string[] = [
    "Arcane Sanctum of Astoria",
    "Order of the Crystal Arcanum",
    "Celestial Academy of Sorcery",
    "Guild of the Arcane Ember",
    "Mystic Consortium of Eldoria",
    "Astral Academy of Enchantment",
    "Covenant of the Silver Moon",
    "Sanctum of the Emerald Flame",
    "Academy of Mystical Lore",
    "Guild of the Crimson Spell",
    "Council of Arcane Wisdom",
    "Institute of Arcane Arts",
    "Guildhall of the Sapphire Star",
    "Circle of the Eternal Flame",
    "Society of the Golden Glyph",
    "Sanctum of the Verdant Grove",
    "Consortium of Astral Magi",
    "Order of the Shadowed Veil",
    "Institute of Celestial Magics",
    "Guild of the Ancient Runes",
    "Arcanum Sanctum of Everfall",
    "Council of the Astral Serpent",
    "Academy of the Azure Skies",
    "Covenant of the Sacred Grove",
    "Sanctum of the Obsidian Moon",
    "Circle of the Ethereal Veil",
    "Guild of the Whispering Winds",
    "Society of the Twilight Arcanum",
    "Celestial Sanctum of Astraea",
    "Institute of Arcane Illumination",
    "Order of the Crimson Phoenix",
    "Guild of the Silver Shroud",
    "Covenant of the Twilight Star",
    "Academy of the Ethereal Essence",
    "Sanctum of the Ruby Dawn",
    "Consortium of the Arcane Citadel",
    "Circle of the Mystic Grove",
    "Guild of the Whispering Shadow",
    "Society of the Ivory Tower",
    "Institute of the Eternal Flame",
    "Order of the Astral Phoenix",
    "Sanctum of the Moonlit Whisper",
    "Academy of the Verdant Arcana",
    "Guild of the Celestial Phoenix",
    "Covenant of the Sapphire Serpent",
    "Society of the Astral Whisper",
    "Circle of the Emerald Eye",
    "Institute of the Crimson Tide",
    "Order of the Ethereal Ember",
    "Sanctum of the Celestial Sentinel"
];

export const fireWizardNames: string[] = [
    "Pyrona Flamecaster",
    "Ignatius Fireweaver",
    "Emberlyn Blazeheart",
    "Inferno Pyrewind",
    "Firesong Emberwitch",
    "Blaze Infernus",
    "Flareon Pyroforge",
    "Scorchia Emberglow",
    "Flamara Firestorm",
    "Ignis Pyrebane",
    "Flamelord Pyrograsp",
    "Pyra Flametongue",
    "Ardent Emberflame",
    "Firebrand Pyrolight",
    "Volcania Blazewind",
    "Infernia Pyrethorn",
    "Pyralis Flamebinder",
    "Flamewing Infernus",
    "Cinder Emberkin",
    "Blazeflare Pyroblade"
];

export const waterWizardNames: string[] = [
    "Aquarius Seawalker",
    "Marina Oceandream",
    "Tidalis Wavecaller",
    "Aquanis Deepstream",
    "Coralia Tidecaster",
    "Nereus Seafarer",
    "Ondine Oceanwhisper",
    "Triton Seastorm",
    "Marella Mistweaver",
    "Lorelei Riverflow",
    "Abyssia Deepdive",
    "Neptuna Tidepool",
    "Undine Seashade",
    "Marinus Aquanaut",
    "Cascade Torrentfall",
    "Nautilus Deepsea",
    "Oceana Wavecrest",
    "Azurel Watervale",
    "Aqualia Seabreeze",
    "Hydrus Aquashard"
];

export const airWizardNames: string[] = [
    "Aerona Windwhisper",
    "Zephyrus Skydancer",
    "Vayu Mistcaller",
    "Sylphina Breezeweaver",
    "Galeon Airheart",
    "Aeronaut Windstrider",
    "Zephyra Cloudwalker",
    "Aeroth Skywatcher",
    "Aeris Stormchaser",
    "Eurus Skyshaper",
    "Aerilyn Windrider",
    "Aurael Skyweaver",
    "Anemone Windrose",
    "Aerona Skygazer",
    "Zephyrine Airglider",
    "Aeron Skyborne",
    "Alizeh Airsinger",
    "Aerion Airbound",
    "Caelum Windbringer",
    "Zephyr Skywanderer"
];

export const earthWizardNames: string[] = [
    "Terra Stoneweaver",
    "Gaius Earthbinder",
    "Gaia Greenleaf",
    "Oren Earthshaper",
    "Grendon Earthsong",
    "Arborea Rootweaver",
    "Sylvan Earthheart",
    "Terranor Rockforge",
    "Rhiannon Earthwalker",
    "Geode Gemcaster",
    "Terrance Dustbringer",
    "Gaian Earthmeld",
    "Tremor Stonehammer",
    "Briar Earthbloom",
    "Gorrum Earthgrasp",
    "Talus Ironroot",
    "Gaiana Earthenheart",
    "Tarron Earthwarden",
    "Terrafera Soilseer",
    "Moss Earthsong"
];